shope/coreapp/urls.py
from django.urls import path
from .views import IndexView

app_name = 'coreapp'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    # path('clear_cache/<str:cache_name>', clear_cache, name="clear_cache"),
]

shope/productsapp/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from productsapp.views import (
    ProductListView,
    AddReviewView,
    ProductComparisonView,
    ProductDetailView,
    AddToComparisonView,
    RemoveFromComparisonView,
    export_product_to_xls,
    DiscountsListView,
    DiscountSetDetailView,
    DiscountCartDetailView,
    seller_detail_view,
)

app_name = 'productsapp'

urlpatterns = [
    path('catalog/', ProductListView.as_view(), name="catalog"),
    path('catalog/<int:product_id>/', ProductDetailView.as_view(), name="product_detail"),
    path('catalog/<int:product_id>/add_review/', AddReviewView.as_view(), name="add_review"),
    path('catalog/<int:product_id>/add_to_comparison/', AddToComparisonView.as_view(), name="add_to_comparison"),
    path('catalog/export/', export_product_to_xls, name="export_product"),
    path('comparison/', ProductComparisonView.as_view(), name="comparison"),
    path('comparison/<int:product_id>', RemoveFromComparisonView.as_view(), name="remove_from_comp"),
    path('sale/', DiscountsListView.as_view(), name="sales"),
    path('sale/<int:elem_id>/set/', DiscountSetDetailView.as_view(), name="discount_set_detail"),
    path('sale/<int:elem_id>/cart/', DiscountCartDetailView.as_view(), name="discount_cart_detail"),
    path('sellers/<int:seller_id>/', cache_page(timeout=86400,
                                                key_prefix="seller_detail"
                                                )(seller_detail_view), name="seller_detail"),
]

shope/shope/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
import os
from django.conf.urls.i18n import i18n_patterns

urlpatterns = []

urlpatterns += i18n_patterns(
    path('', include('coreapp.urls')),
    path('admin/', admin.site.urls),
    path('order/', include('orderapp.urls')),
    path('profile/', include('profileapp.urls')),
    path('products/', include('productsapp.urls')),
    path('payment/', include('paymentapp.urls')),
    path('auth/', include('authapp.urls')),
    path('cart/', include('cartapp.urls')),
)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

if not os.getenv("DOCKER"):
    urlpatterns += [path('silk/', include('silk.urls', namespace='silk'))]

shope/productsapp/models/banner.py
from django.db import models
from coreapp.models import BaseModel
from productsapp.models import Category
from django.utils.translation import gettext_lazy as _


class Banner(BaseModel):
    """
    Класс-модель баннеров на главной странице
    """
    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
        verbose_name=_('category'),
        related_name='category_on_banner'
    )

    image = models.ImageField(
        upload_to='banners_images/',
        verbose_name=_('image')
    )

    class Meta:
        verbose_name = _("banner")
        verbose_name_plural = _("banners")

    def __str__(self):
        return self.category.name

    @property
    def category_min_price(self):
        return None

shope/productsapp/models/category.py
from django.db import models
from coreapp.models import BaseModel
from django.utils.translation import gettext_lazy as _


class Category(BaseModel):
    """
    Класс-модель для определения категории продукта
    """
    name = models.CharField(max_length=100,
                            null=False,
                            blank=True,
                            verbose_name=_("name"))

    icon = models.FileField(
        upload_to='categories_icons/',
        null=True,
        blank=True,
        verbose_name=_('icon (SVG)'))

    class Meta:
        verbose_name = _("category")
        verbose_name_plural = _("categories")

    def __str__(self):
        return self.name

shope/productsapp/models/seller.py
from django.db import models

from coreapp.models import BaseModel
from authapp.models import User
from django.utils.translation import gettext_lazy as _


class Seller(BaseModel):
    """
    Класс-модель продавца
    """
    name = models.CharField(
        max_length=100,
        verbose_name=_('name')
    )

    owner = models.ForeignKey(
        User,
        null=True,
        on_delete=models.CASCADE,
        related_name=_('companies'),
        verbose_name=_('owner'))

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _("seller")
        verbose_name_plural = _("sellers")

shope/productsapp/forms/add_review_form.py
from django import forms
from productsapp.models import Review
from django.utils.translation import gettext_lazy as _


class AddReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = "text",

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["text"].widget.attrs["class"] = "form-textarea"
        self.fields["text"].widget.attrs["name"] = "review"
        self.fields["text"].widget.attrs["id"] = "review"
        self.fields["text"].widget.attrs["placeholder"] = _("Review")

shope/productsapp/forms/catalog_filter_form.py
from django import forms
import re
from coreapp.enums import SORT_TYPES


class CatalogFilterForm(forms.Form):
    """
    Форма валидации параметров фильтра в каталоге
    """
    query = forms.CharField(max_length=50, required=False)
    category = forms.CharField(max_length=30, required=False)
    price_range = forms.CharField(max_length=30, required=False)
    free_delivery = forms.BooleanField(required=False)
    in_stock = forms.BooleanField(required=False)
    discounted = forms.BooleanField(required=False)
    sort = forms.CharField(max_length=20, required=False)
    tag = forms.CharField(max_length=50, required=False)
    price_min = forms.IntegerField(min_value=0, required=False)
    price_max = forms.IntegerField(min_value=0, required=False)

    def clean(self):
        """
        Проверка корректности и нормализация диапазона цены,
        в противном случае ценовой диапазон не учитывается в фильтре
        """
        cleaned_data = super().clean()
        price_range = cleaned_data.get('price_range')
        if re.fullmatch(r'^\d+;\d+$', price_range):
            price_min, price_max = map(int, price_range.split(';'))
            if price_min < price_max:
                cleaned_data['price_min'] = price_min
                cleaned_data['price_max'] = price_max
        return cleaned_data

    def clean_sort(self):
        """
        Проверка корректности параметра сортировки,
        в противном случае применяется значение по умолчанию
        """
        sort = self.cleaned_data.get('sort')
        if sort in SORT_TYPES:
            return sort
        else:  # параметр sort отуствтует или некорректен
            return '-reviews'

shope/productsapp/views/add_review_view.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import redirect
from django.urls import reverse
from django.views import View
from productsapp.forms import AddReviewForm
from coreapp.utils.add_product_review import AddProductReview
from repositories.price_repository import PriceRepository
from repositories.product_select_repository import ProductSelectRepository
from repositories.profile_repository import ProfileRepository
from repositories import SellerSelectRepository, SpecificSelectRepository

_profile_repository = ProfileRepository()
_product_repository = ProductSelectRepository()
select_seller_repo = SellerSelectRepository()
select_specifics_repo = SpecificSelectRepository()
_price_repository = PriceRepository()


class AddReviewView(View):
    """
    Класс-view для добавления отзыва к продукту
    """
    form_class = AddReviewForm
    _service = AddProductReview()

    def post(self,
             request: HttpRequest,
             product_id: int) -> HttpResponse:
        form = self.form_class(data=request.POST)  # форма с отзывом
        product = _product_repository.get_product_by_id(
            product_id=product_id
        )
        if request.user.is_authenticated:
            if form.is_valid():
                # Если форма валидна и юзер авторизован, берем отзыв и добавляем к продукту.
                text = form.cleaned_data.get("text")
                self._service.add_product_review(
                    user=_profile_repository.get_profile(request.user),
                    product=product,
                    text=text
                )
        return redirect(reverse("productsapp:product_detail",
                                kwargs={"product_id": product.pk}))

shope/productsapp/views/add_to_comparison.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from django.views import View

from coreapp.utils import ViewedProductsService
from coreapp.utils.add_product_review import AddProductReview
from coreapp.utils.products_comparison_list import ProductsComparisonList
from productsapp.forms import AddReviewForm
from repositories import SellerSelectRepository, \
    SpecificSelectRepository, ProductSelectRepository
from repositories.price_repository import PriceRepository
from repositories.product_image_repository import ProductImageRepository

_select_seller_repo = SellerSelectRepository()
_select_specifics_repo = SpecificSelectRepository()
_price_repository = PriceRepository()
_product_image_repo = ProductImageRepository()
_product_repo = ProductSelectRepository()


class AddToComparisonView(View):
    """
    Представление для добавления товара в список сравнения
    """

    _comparison_service = ProductsComparisonList()
    _review_service = AddProductReview()
    _viewed_service = ViewedProductsService()

    template_name = "productsapp/product.html"
    form_class = AddReviewForm

    def get(self, request: HttpRequest, product_id: int) -> HttpResponse:
        product = _product_repo.get_product_by_id(product_id)
        # получаем конкретный продукт
        product_price = _price_repository. \
            get_min_price_object(product=product)
        amount_review = self._review_service.product_reviews_amount(product=product)
        # количество отзывов
        reviews_list = self._review_service.product_reviews_list(
            product=product,
            count=1)
        # список отзывов
        sellers = _select_seller_repo.get_seller_by_product(
            product=product
        )
        specifics = _select_specifics_repo.get_specific_by_product(
            product=product
        )
        if request.user.is_authenticated:
            self._viewed_service.add_to_viewed_products(
                user=request.user,
                product=product
            )

        product_images = _product_image_repo.get_all_images(product=product)

        return render(request, self.template_name,
                      context={"product": product,
                               "product_images": product_images,
                               "form": self.form_class,
                               "product_price": product_price,
                               "amount_review": amount_review,
                               "reviews_list": reviews_list,
                               'sellers': sellers,
                               'specifics': specifics,
                               "user": request.user})

    def post(self, request: HttpRequest, product_id: int) -> HttpResponse:

        product = _product_repo.get_product_by_id(product_id)
        product_images = _product_image_repo.get_all_images(product=product)
        product_price = _price_repository. \
            get_min_price_object(product=product)
        amount_review = self._review_service.product_reviews_amount(product=product)
        reviews_list = self._review_service.product_reviews_list(product=product)
        category_in_comp = self._comparison_service.\
            get_comparison_list(request).first()
        cur_category = product.category
        error_category = False
        if category_in_comp is None or \
                category_in_comp.category == cur_category:
            self._comparison_service.add_to_comparison(
                request=request,
                product_id=product_id
            )
        elif category_in_comp and \
                category_in_comp.category != cur_category:
            error_category = True

        return render(request, self.template_name,
                      context={"product": product,
                               "product_images": product_images,
                               "product_price": product_price,
                               "amount_review": amount_review,
                               "reviews_list": reviews_list,
                               "form": self.form_class,
                               "error_category": error_category})

shope/productsapp/views/discount_detail_view.py
from django.http import HttpResponse, HttpRequest
from django.shortcuts import render
from django.views import View

from repositories import DiscountRepository, PriceRepository

_discount_repo = DiscountRepository()
_price_repository = PriceRepository()


class DiscountSetDetailView(View):
    """
    Представление для отображения
    детальной страницы скидки на набор продуктов
    """
    template_name = "productsapp/detailed_discount.html"

    def get(self, request: HttpRequest, elem_id: int) -> HttpResponse:
        set_discount = _discount_repo.get_set_discount_by_id(elem_id)
        for product in set_discount.products.all():
            product_price = _price_repository. \
                get_min_price_object(product=product).value
            product.price = product_price
        context = {
            "set_discount": set_discount,
        }
        return render(request=request,
                      template_name=self.template_name,
                      context=context)


class DiscountCartDetailView(View):
    """ Представление для отображения детальной страницы скидки на корзину """

    template_name = "productsapp/detailed_discount.html"

    def get(self, request: HttpRequest, elem_id: int) -> HttpResponse:
        cart_discount = _discount_repo.get_cart_discount_by_id(elem_id)
        context = {
            "cart_discount": cart_discount,
        }
        return render(request=request,
                      template_name=self.template_name,
                      context=context)

shope/productsapp/views/discounts_list_view.py
from itertools import chain
from django.views.generic import View
from django.shortcuts import render
from repositories.discount_select_repository import DiscountRepository
from django.core.paginator import Paginator
from django.http import HttpResponse
from coreapp.utils import ProductDiscounts
rep_discount = DiscountRepository()


class DiscountsListView(View):
    """
    Класс для отображения всех скидок
    """
    template_name = 'productsapp/sale.html'
    paginate_by = 12

    def get(self, request, *args, **kwargs) -> HttpResponse:
        """
        Метод для отображения всех имеющихся скидок
        """
        set_discounts = rep_discount.get_set_discounts_all()
        cart_discounts = rep_discount.get_cart_discounts_all()
        products_discounts = rep_discount.get_products_discounts_all()
        products, categories = ProductDiscounts.\
            get_objects_discounts_list(products_discounts)
        result_list = list(chain(cart_discounts, set_discounts,
                                 *categories, *products))
        # общий список всех скидок на товары, корзины, наборы товаров
        paginator = Paginator(result_list, self.paginate_by)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        context = {'page_obj': page_obj}
        return render(request, self.template_name, context)

shope/productsapp/views/export_product.py
from io import BytesIO
from django.http import HttpRequest, HttpResponse
import pandas as pd
from repositories import ProductSelectRepository

_product_repository = ProductSelectRepository()


def export_product_to_xls(request: HttpRequest) \
        -> HttpResponse:
    products = _product_repository.get_all_products()
    excel_file = BytesIO()
    excel_writer = pd.ExcelWriter(excel_file)
    result = dict()
    for product in products:
        for name_field in product._meta.fields:
            if name_field.name not in result.keys():
                result[name_field.name] = list()
            if name_field.name not in (
                    "created_at",
                    "updated_at",
            ):
                result[name_field.name].append(
                    product.__getattribute__(str(name_field.name))
                )
            else:
                result[name_field.name].append(
                    product.__getattribute__(
                        str(name_field.name)
                    ).isoformat(sep=" ")
                )
    df = pd.DataFrame(
        result
    )
    df.to_excel(excel_writer, sheet_name='products')
    excel_writer.close()
    excel_file.seek(0)

    response = HttpResponse(
        excel_file.read(),
        content_type='application/vnd.openxmlformats-'
                     'officedocument.spreadsheetml.sheet',
    )
    response[
        'Content-Disposition'
    ] = 'attachment; filename=products.xlsx'
    response['Set-Cookie'] = 'fileDownload=true; path=/'
    return response

shope/templates/productsapp/button_to_start_importing.html
{% extends 'admin/change_list.html' %}
{% load i18n %}
{% block object-tools-items %}
    <li>
        <a href="{% url 'admin:run_background_imports' %}" class="historylink">{% translate 'Run a background import of goods' %}</a>
    </li>
    {{ block.super }}
{% endblock %}

shope/templates/productsapp/detailed_seller.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block title %}
    Megano
{% endblock %}


{% block Header-slider %}
{% endblock %}

{% block content %}
    <div class="Middle Middle_top">
    <div class="Section">
        <div class="wrap">
            <h1 style="text-align: center">{{ seller.name }}</h1>
            <div class="Middle Middle_top">
                <div class="Section">
                    <div class="wrap">
                        <div class="Cart-total">
                            <div class="Cart-block Cart-block_total">
                                <strong class="Cart-title">{% translate 'Name' %}:
                                </strong><span class="Cart-price">{{ seller.name }}</span>
                            </div>
                        </div>
                        <div class="Cart-total">
                            <div class="Cart-block Cart-block_total">
                                <strong class="Cart-title"
                                        style="margin-bottom: 2em">{% translate 'Products' %}:</strong>
                                {% for product in products %}
                                    <div class="Cart-product">
                                        <div class="Cart-block Cart-block_row">
                                            <div class="Cart-block Cart-block_pict">
                                                <a class="Cart-pict"
                                                   href="{% url 'productsapp:product_detail' product.pk %}">
                                                    <img class="Cart-img"
                                                         src="{{ product.product_images.first.image.url }}"
                                                         alt="card.jpg"/>
                                                </a>
                                            </div>
                                            <div class="Cart-block Cart-block_info"><a class="Cart-title"
                                                                                       href="{% url 'productsapp:product_detail' product.pk %}">{{ product.name }}</a>
                                                <div class="Cart-desc">{{ product.short_description }}
                                                </div>
                                            </div>
                                            <div class="Cart-block Cart-block_price">
                                                <div class="Cart-price">{{ product.price }}
                                                </div>
                                            </div>
                                        </div>
                                        <div class="Cart-block Cart-block_row">
                                            <div class="Cart-block Cart-block_seller">
                                                <!-- - var options = setOptions(items, ['value', 'selected', 'disabled']);-->

                                            </div>
                                            <div class="Cart-block Cart-block_amount">
                                                <div class="Cart-amount">
                                                    <div class="Amount">

                                                    </div>
                                                </div>
                                            </div>
                                            <div class="Cart-block Cart-block_delete">

                                            </div>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
{% endblock %}

shope/templates/productsapp/sale.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% load get_object_date %}
{% block title %}
Megano
{% endblock %}


{% block Header-slider %}
{% endblock %}

{% block content %}
<div class="Middle Middle_top">
    <div class="Middle-top">
        <div class="wrap">
            <div class="Middle-header">
                <ul class="breadcrumbs Middle-breadcrumbs">
                    <li class="breadcrumbs-item"><a href="{% url 'coreapp:index' %}">{% translate 'Home' %}</a>
                    </li>
                    <li class="breadcrumbs-item breadcrumbs-item_current"><span>{% translate 'Blog' %}</span>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="Section">
        <div class="wrap">
            <div class="Cards Cards_blog">
                {% for object in page_obj %}
                <div class="Card">
                    {% if object.type == "cart" %}
                    <a class="Card-picture" href="{% url 'productsapp:discount_cart_detail' object.pk %}">
                        <img src="{% static 'discounts_image/carts_sales.jpg' %}" alt=""/>
                    </a>
                    {% elif object.type == "set" %}
                    <a class="Card-picture" href="{% url 'productsapp:discount_set_detail' object.pk %}">
                        <img src="{% static 'discounts_image/sets_sales.jpg' %}" alt=""/>
                    </a>
                    {% elif object.type == "product" %}
                    <a class="Card-picture" href="{% url 'productsapp:product_detail' object.pk %}">
                        <img src="{{object.product_images.first.image.url}}" alt=""/>
                    </a>
                    {% else %}
                    <a class="Card-picture" href="{% url 'productsapp:catalog' %}?category={{object.name}}">
                        <img src="{{object.category_products.first.product_images.last.image.url}}" alt=""/>
                    </a>
                    {% endif %}
                    {% if object.type == "product" or object.type == "category" %}
                    {% get_object_date object.start_date as start_date %}
                    <div class="Card-date">
                        <strong class="Card-date-number">{{ start_date |date:"j" }}</strong>
                        <span class="Card-date-month">{{ start_date |date:"b" }}</span>
                    </div>
                    {% if object.expiration_date %}
                    {% get_object_date object.expiration_date as expiration_date %}
                    <div class="Card-date Card-date_to">
                        <strong class="Card-date-number">{{ expiration_date |date:"j" }}</strong>
                        <span class="Card-date-month">{{ expiration_date |date:"b" }}</span>
                    </div>
                    {% endif %}
                    {% else %}
                    <div class="Card-date">
                        <strong class="Card-date-number">{{ object.start_date |date:"j" }}
                        </strong><span class="Card-date-month">{{ object.start_date |date:"b" }}</span>
                    </div>
                    {% if cart.expiration_date %}
                    <div class="Card-date Card-date_to">
                        <strong class="Card-date-number">{{ object.expiration_date |date:"j" }}
                        </strong><span class="Card-date-month">{{ object.expiration_date |date:"b" }}</span>
                    </div>
                    {% endif %}
                    {% endif %}
                    {% if object.type == "product" %}
                    <div class="Card-content">
                        <!--                        <div class="Card-pin"></div>-->
                        <strong class="Card-title"><a href="{% url 'productsapp:product_detail' object.pk %}">{{object.name}}</a>
                        </strong>
                        <div class="Card-description">{% translate 'Discount' %} - {{object.value}} %
                        </div>
                    </div>
                    {% elif object.type == "category" %}
                    <div class="Card-content">
                        <strong class="Card-title"><a href="{% url 'productsapp:catalog' %}?category={{object.name}}">
                            {%translate 'Category' %} - {{object.name}}</a>
                        </strong>
                        <div class="Card-description">{% translate 'Discount on product category'%} -
                            {{object.value}} %
                        </div>
                    </div>
                    {% elif object.type == "set" %}
                    <div class="Card-content">
                        <strong class="Card-title"><a
                                href="{% url 'productsapp:discount_set_detail' object.pk %}">{{object.name}}</a>
                        </strong>
                        <div class="Card-description">{{object.description}}</div>
                    </div>
                    {% else %}
                    <div class="Card-content">
                        <strong class="Card-title"><a
                                href="{% url 'productsapp:discount_cart_detail' object.pk %}">{{object.name}}</a>
                        </strong>
                        <div class="Card-description">{{object.description}}</div>
                    </div>
                    {% endif %}
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
<div class="Pagination">
    <div class="Pagination-ins">
        <a class="Pagination-element"
           href="{% url 'productsapp:sales' %}?page=1">
            <span class="Pagination-text">1</span>
        </a>
        {% if page_obj.has_previous %}
        <a class="Pagination-element Pagination-element_prev"
           href="{% url 'productsapp:sales' %}?page={{page_obj.previous_page_number}}">
            <img src="{% static 'assets/img/icons/prevPagination.svg' %}" alt="prevPagination.svg"/>
        </a>
        {% else %}
        <a class="Pagination-element Pagination-element_prev">
            <img src="{% static 'assets/img/icons/prevPagination.svg' %}" alt="prevPagination.svg"/>
        </a>
        {% endif %}
        <a class="Pagination-element Pagination-element_current" href="">
            <span class="Pagination-text">{{page_obj.number}}</span>
        </a>
        {% if page_obj.has_next %}
        <a class="Pagination-element Pagination-element_prev"
           href="{% url 'productsapp:sales' %}?page={{page_obj.next_page_number}}">
            <img src="{% static 'assets/img/icons/nextPagination.svg' %}" alt="nextPagination.svg"/>
        </a>
        {% else %}
        <a class="Pagination-element Pagination-element_prev">
            <img src="{% static 'assets/img/icons/nextPagination.svg' %}" alt="nextPagination.svg"/>
        </a>
        {% endif %}
        <a class="Pagination-element"
           href="{% url 'productsapp:sales' %}?page={{page_obj.paginator.num_pages}}">
            <span class="Pagination-text">{{page_obj.paginator.num_pages}}</span>
        </a>
    </div>
</div>
{% endblock %}