shope/authapp/urls.py
from django.urls import path
from authapp.views import UserLoginView, UserLogoutView, UserSignUpView, \
    verify_user, UserPassResetView, UserPassChangeView

app_name = 'authapp'

urlpatterns = [
    path('forgot-password/', UserPassResetView.as_view(),
         name='forgot_pass'),
    path('login/', UserLoginView.as_view(),
         name='login'),
    path('set-password/<uidb64>/<token>/', UserPassChangeView.as_view(),
         name='set_pass'),
    path('signup/', UserSignUpView.as_view(),
         name='signup'),
    path('logout/', UserLogoutView.as_view(),
         name='logout'),
    path('verified/<str:email>/<str:key>/', verify_user,
         name='verified'
         ),
]

shope/coreapp/urls.py
from django.urls import path
from .views import IndexView

app_name = 'coreapp'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    # path('clear_cache/<str:cache_name>', clear_cache, name="clear_cache"),
]

shope/shope/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
import os
from django.conf.urls.i18n import i18n_patterns

urlpatterns = []

urlpatterns += i18n_patterns(
    path('', include('coreapp.urls')),
    path('admin/', admin.site.urls),
    path('order/', include('orderapp.urls')),
    path('profile/', include('profileapp.urls')),
    path('products/', include('productsapp.urls')),
    path('payment/', include('paymentapp.urls')),
    path('auth/', include('authapp.urls')),
    path('cart/', include('cartapp.urls')),
)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

if not os.getenv("DOCKER"):
    urlpatterns += [path('silk/', include('silk.urls', namespace='silk'))]

shope/authapp/models.py
import pytz
from django.db import models
from datetime import datetime, timedelta
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """
    Класс модели пользователя
    """
    username = models.CharField(_("username"), max_length=150,
                                null=True, blank=True)
    middle_name = models.CharField(_("middle name"),
                                   max_length=150,
                                   blank=True)
    email = models.EmailField(_("email address"),
                              unique=True)  # переопределение
    # email с целью сделать это поле уникальным
    activation_key = models.CharField(max_length=50, blank=True)
    # ключ для активации аккаунта
    activation_key_expires = models.DateTimeField(auto_now=True,
                                                  blank=True,
                                                  null=True)
    # формируется при создании экземпляра модели

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ['username']

    @property
    def is_activation_key_expires(self):
        """
        Метод, который проверяет, попадает ли ввод ключа
        в установленный временной интервал
        return: Bool
        """
        if datetime.now().replace(tzinfo=pytz.utc) \
                <= (self.activation_key_expires + timedelta(hours=72)):
            # если текущая дата не превышает даты создания ключа активации
            # более чем на 72 часа
            return False
        else:
            return True

    def __str__(self):
        return self.first_name + ' ' + self.last_name

# Create your models here.

shope/authapp/forms.py
from django import forms
from authapp.models import User
from django.contrib.auth.forms import AuthenticationForm, \
    UserCreationForm, UsernameField, SetPasswordForm, \
    PasswordResetForm
from django.utils.translation import gettext_lazy as _
from django.contrib.auth import authenticate
from django.core.exceptions import ObjectDoesNotExist
from django.template import loader
from .tasks import send_link_for_password


class UserLoginForm(AuthenticationForm):
    """
    Форма для авторизации пользователя
    """
    username = UsernameField(
        widget=forms.TextInput(
            attrs={"autofocus": True,
                   "placeholder": "e-mail"
                   })
    )
    password = forms.CharField(
        label="Password",
        strip=False,
        widget=forms.
        PasswordInput(
            attrs={"autocomplete": "current-password",
                   "placeholder": "********"
                   })
    )

    class Meta:
        model = User
        fields = ('username', 'password')

    def clean(self):
        """
        Переопределение метода для отображения ошибки при неактивном
        пользователе
        """
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        if username is not None and password:
            self.user_cache = authenticate(
                self.request, username=username, password=password
            )
            if self.user_cache is None:
                try:  # попытка найти пользователя с таким email
                    user_not_active = User.objects.get(email=username)
                except ObjectDoesNotExist:
                    user_not_active = None
                if user_not_active is not None and \
                        user_not_active.check_password(password):
                    # если пользователь с таким username(email) существует,
                    # и введён верный пароль, но его учетная запись неактивна
                    self.confirm_login_allowed(user_not_active)
                else:
                    raise self.get_invalid_login_error()
        return self.cleaned_data


class UserSignUpForm(UserCreationForm):
    """
    Форма для регистрации пользователя
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].widget.attrs['placeholder'] = 'E-mail'
        self.fields['password1'].widget.attrs['placeholder'] = _('Password')
        self.fields['password2'].widget. \
            attrs['placeholder'] = _('Password confirmation')
        self.fields['first_name'].widget.attrs['placeholder'] = _('Name')
        self.fields['last_name'].widget.attrs['placeholder'] = _('Surname')
        self.fields['middle_name'].widget.attrs['placeholder'] = _('Middle name')  # noqa
        self.fields['last_name'].required = True
        self.fields['first_name'].required = True
        for name_field, field in self.fields.items():
            field.widget.attrs['class'] = 'user-input'

    class Meta:
        model = User
        fields = ('email', 'first_name',
                  'middle_name', 'last_name')


class UserResetPasswordForm(PasswordResetForm):
    """
    Форма для ввода email
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].widget.attrs['placeholder'] = 'E-mail'

    def send_mail(
            self,
            subject_template_name,
            email_template_name,
            context,
            from_email,
            to_email,
            html_email_template_name=None,
    ):
        """
        Метод для отправки сообщения на e-mail
        """
        subject = loader.render_to_string(subject_template_name, context)
        # Тема письма не должна содержать новых строк
        subject = "".join(subject.splitlines())
        body = loader.render_to_string(email_template_name, context)
        html_email = loader.render_to_string(html_email_template_name, context)
        send_link_for_password.delay(
            subject, body,
            from_email, to_email, html_email
        )  # отправка сообщения на e-mail


class UserSetPasswordForm(SetPasswordForm):
    """
    Форма для ввода нового пароля
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['new_password1'].widget.attrs['placeholder'] = _('Password')  # noqa
        self.fields['new_password2'].widget. \
            attrs['placeholder'] = _('Password confirmation')

shope/profileapp/forms/set_password_form.py
from django import forms
from django.contrib.auth.forms import SetPasswordForm
from django.contrib.auth import password_validation
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _


class UserPasswordSetForm(SetPasswordForm):
    """
    A form that lets a user set their password without entering the old
    password
    """

    new_password1 = forms.CharField(
        label=_("New password"),
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        strip=False,
        required=False,
        help_text=password_validation.password_validators_help_text_html(),
    )
    new_password2 = forms.CharField(
        label=_("New password confirmation"),
        strip=False,
        required=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
    )

    def clean_new_password2(self):
        password1 = self.cleaned_data.get("new_password1")
        password2 = self.cleaned_data.get("new_password2")

        if password1 or password2:
            if password1 != password2:
                raise ValidationError(
                    self.error_messages["password_mismatch"],
                    code="password_mismatch",
                )
            password_validation.validate_password(password2, self.user)
        return password2

    def save(self, commit=True):
        password = self.cleaned_data["new_password1"]
        if password:
            self.user.set_password(password)
            if commit:
                self.user.save()
        return self.user

shope/authapp/views.py
from authapp.models import User
from django.shortcuts import render
from django.contrib import messages
from django.conf import settings
from django.contrib.auth import login
from django.contrib.auth.views import PasswordResetView, \
    PasswordResetConfirmView
from django.views.generic import CreateView
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy, \
    reverse
from authapp.forms import UserLoginForm, UserSignUpForm, \
    UserResetPasswordForm, UserSetPasswordForm
from django.contrib.auth.views import LoginView, LogoutView
from .tasks import send_verif_link
from coreapp.utils import AddToCart, generate_random_string
from repositories.cart_repository import RepCart
from django.utils.translation import gettext_lazy as _
from django.http import HttpResponse
from django.contrib.sites.shortcuts import get_current_site
messages_dict = {
    'reg_success': _(
        'You have successfully registered. '
        '\nThe account activation link has been emailed to you.'
        '\n You must confirm your account within 72 hours.'),
    'pass_link': _('Link to change your password '
                   'was sent to your email address'),
    'pass_change_success': _('Your password has been successfully changed'),
    'activate_error': _('An error has occurred. '
                        'The activation period has expired'
                        '\nTry registering again.'),
    'email_confirm': _('Email confirmation on')
}


class UserLoginView(LoginView):
    """
    Авторизация пользователя.
    """
    template_name = 'authapp/login.html'
    form_class = UserLoginForm
    redirect_authenticated_user = True

    def form_valid(self, form: UserLoginForm):
        """
        Метод, вызываемый при валидации формы
        """
        super().form_valid(form)
        session_products = self.request.session.get('products')
        if self.request.user.is_authenticated and session_products:
            # если в сессии есть продукты
            AddToCart.move_from_session(self.request.user, session_products)
            # добавление товаров в корзину пользователя из сессии
        return HttpResponseRedirect(self.get_success_url())


class UserLogoutView(LogoutView):
    """
    Выход пользователя из учётной записи
    """
    next_page = '/'


class UserSignUpView(CreateView):
    """
    Регистрация пользователя
    """
    model = User
    template_name = 'authapp/registr.html'
    form_class = UserSignUpForm
    success_url = reverse_lazy('authapp:login')
    rep_cart = RepCart()

    def get(self, request, *args, **kwargs) \
            -> HttpResponse:
        """
        Метод для отображения страницы регистрации и формы
        """
        form = self.form_class(data=request.GET)
        if request.user.is_authenticated:
            return HttpResponseRedirect(reverse('coreapp:index'))
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs) -> HttpResponse:
        form = self.form_class(data=request.POST)
        if form.is_valid():  # форма прошла валидацию
            user = form.save(commit=False)
            user.is_active = False  # деактивация пользователя
            user.activation_key = generate_random_string()
            user.save()
            current_site = get_current_site(request)
            site_name = current_site.name
            protocol = request.scheme
            domain = current_site.domain
            send_verif_link.delay(protocol, domain, site_name, user.email,
                                  user.activation_key,
                                  user.first_name, user.last_name)
            # ссылка создана и отправлено сообщение
            messages.success(request, messages_dict['reg_success'])
            return HttpResponseRedirect(reverse('authapp:login'))
        else:  # при наличии ошибок в форме
            messages.error(request, *list(form.errors.values()))
        return render(request, self.template_name, {'form': form})


def verify_user(request, **kwargs) -> HttpResponse:
    """
    Активация учетной записи
    :return: Response
    :rtype: HttpResponse
    """
    if request.method == 'GET':
        email = kwargs.get('email')  # мейл из запроса
        activate_key = kwargs.get('key')  # ключ из запроса
        user = User.objects.get(email=email)
        if user and user.activation_key == activate_key:
            if not user.is_activation_key_expires:
                # если еще не прошло 72 часа
                # с момента регистрации и ключи одинаковые
                user.activation_key = ""
                user.is_active = True  # активация пользователя
                user.activation_key_expires = None
                user.save()
                login(request, user)  # вход в учетную запись
                session_products = request.session.get('products')
                AddToCart.move_from_session(user, session_products)
            else:
                messages.error(request, messages_dict['activate_error'])
    return HttpResponseRedirect(reverse('coreapp:index'))


class UserPassResetView(PasswordResetView):
    """
    Класс для отработки отправки токена для смены пароля на
    электронную почту.
    """
    form_class = UserResetPasswordForm
    template_name = "authapp/forgot_password.html"
    from_email = settings.EMAIL_HOST_USER
    html_email_template_name = "authapp/email/reset_confirm.html"
    email_template_name = 'authapp/email/reset_confirm.html'
    success_url = reverse_lazy('authapp:login')

    def form_valid(self, form):
        """
        Метод, вызываемый при валидации формы
        """
        messages.success(self.request, messages_dict['pass_link'])
        return super().form_valid(form)


class UserPassChangeView(PasswordResetConfirmView):
    """
    Класс для смены пароля
    """
    form_class = UserSetPasswordForm
    template_name = "authapp/set_password.html"
    success_url = reverse_lazy('authapp:login')

    def form_valid(self, form):
        """
        Метод, вызываемый при валидации формы
        """
        messages.success(self.request, messages_dict['pass_change_success'])
        return super().form_valid(form)

shope/templates/authapp/change_password.html
{% extends 'base.html' %}
{% load static %}
{% block Header-searchWrap %}
{% endblock %}
{% block Header-slider %}
{% endblock %}
{% block wrap %}
<div class="wrap">
    <div class="row Header-rowMain">
        <div class="row-block Header-logo"><a class="logo" href="../index.html"><img class="logo-image"
                                                                                     src="{% static 'assets/img/logo.png' %}"
                                                                                     alt="logo.png"/></a>
        </div>
    </div>
</div>
{% endblock %}
{% block content %}
<div class="wrapper">
    <div class="header">
        <h3 class="sign-in">Восстановление пароля (2/2)</h3>
        <h5>Придумайте новый пароль для учетной записи</h5>
    </div>

    <form action="#">
        <div>
            <input type="password" name="pass" id="name" placeholder="Пароль"/>
        </div>
        <div>
            <input type="submit" value="Сохранить пароль"/>
        </div>
    </form>
</div>

{% endblock %}

shope/templates/authapp/e-mail.html
{% extends 'base.html' %}
{% load static %}

{% block Header-searchWrap %}
{% endblock %}

{% block Header-slider %}
{% endblock %}

{% block wrap %}
<div class="wrap">
    <div class="row Header-rowMain">
        <div class="row-block Header-logo"><a class="logo" href="../index.html"><img class="logo-image"
                                                                                     src="{% static 'assets/img/logo.png' %}"
                                                                                     alt="logo.png"/></a>
        </div>
    </div>
</div>
{% endblock %}
{% block content %}
<div class="wrapper">
    <div class="header">
        <h3 class="sign-in">Восстановление пароля (1/2)</h3>
        <h5>Для восстановления пароля введите адрес электронной почты, на которую зарегистрирована учетная
            запись</h5>
    </div>

    <form action="#">

        <div>


            <input class="user-input" type="email" name="login" id="name" placeholder="E-mail"/>
        </div>
        <div>
            <input type="submit" value="Получить проверочный код"/>
        </div>
        <a class="registr" href="1/registr.html">
            Вход
        </a>
    </form>
</div>
{% endblock %}

shope/templates/authapp/email_to_change_password.html
{% extends 'base.html' %}
{% load static %}

{% block Header-searchWrap %}
{% endblock %}

{% block Header-slider %}
{% endblock %}

{% block wrap %}
<div class="wrap">
    <div class="row Header-rowMain">
        <div class="row-block Header-logo"><a class="logo" href="../index.html"><img class="logo-image"
                                                                                     src="{% static 'assets/img/logo.png' %}"
                                                                                     alt="logo.png"/></a>
        </div>
    </div>
</div>
{% endblock %}
{% block content %}
<div class="wrapper">
    <div class="header">
        <h3 class="sign-in">Восстановление пароля (1/2)</h3>
        <h5>Для восстановления пароля введите адрес электронной почты, на которую зарегистрирована учетная
            запись</h5>
    </div>

    <form action="#">

        <div>


            <input class="user-input" type="email" name="login" id="name" placeholder="E-mail"/>
        </div>
        <div>
            <input type="submit" value="Получить проверочный код"/>
        </div>
        <a class="registr" href="1/registr.html">
            Вход
        </a>
    </form>
</div>
{% endblock %}

shope/templates/authapp/forgot_password.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block Header-searchWrap %}
{% endblock %}

{% block Header-slider %}
{% endblock %}

{% block wrap %}
<div class="wrap">
    <div class="row Header-rowMain">
        <div class="row-block Header-logo"><a class="logo" href="{% url 'coreapp:index' %}"><img class="logo-image"
                                                                                     src="{% static 'assets/img/logo.png' %}"
                                                                                     alt="logo.png"/></a>
        </div>
    </div>
</div>
{% endblock %}
{% block content %}
<div class="wrapper">
    <div class="header">
        <h3 class="sign-in">{% translate 'Password recovery (1/2)' %}</h3>
        <h5 class="set-pass">{% translate 'To retrieve your password, enter the e-mail address where your account is registered account' %}</h5>
    </div>

    <form action="{% url 'authapp:forgot_pass' %}" method="post">{% csrf_token %}

        <div>
            {% if form.email.errors %} {{ form.email.errors }} {% endif %}
            {{ form.email }}
            <!--            <input class="user-input" type="email" name="login" id="name" placeholder="E-mail"/>-->
        </div>
        <div>
            <input type="submit" value="{% translate 'Get a verification code' %}"/>
        </div>
        <a class="registr" href="{% url 'authapp:login' %}">
            {% translate 'Log in' %}
        </a>
    </form>
</div>
{% endblock %}

shope/templates/authapp/login.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block Header-searchWrap %}
{% endblock %}

{% block Header-slider %}
{% endblock %}

{% block wrap %}
<div class="wrap">
    <div class="row Header-rowMain">
        <div class="row-block Header-logo"><a class="logo" href="{% url 'coreapp:index' %}"><img class="logo-image"
                                                                                         src="{% static 'assets/img/logo.png' %}"
                                                                                         alt="logo.png"/></a>
        </div>
    </div>
</div>
{% endblock %}
{% block content %}
<div class="wrapper">
    <div class="error-login">
        {% for message in messages %}
            {{ message }}
        {% endfor %}
        {% for error in form.non_field_errors %}
            {{ error }}
        {% endfor %}
    </div>
    <div class="header">
        <h3 class="sign-in">{% translate 'Log in' %}</h3>
    </div>
    <div class="clear"></div>
    <form action="" method="post">{% csrf_token %}
        <div>
            {{ form.username }}
        </div>
        <div>
            {{ form.password }}
        </div>
        <div>
            <input type="submit" value="{% translate 'Log in' %}"/>
        </div>
        <a class="forgot-label" href="{% url 'authapp:forgot_pass' %}">{% translate 'Forgot your password?' %}</a>
        <a class="registr" href="{% url 'authapp:signup' %}">
            {% translate 'Registration' %}
        </a>
    </form>
</div>
{% endblock %}

shope/templates/authapp/mail.html
{% extends 'base.html' %}
{% load static %}

{% block Header-searchWrap %}
{% endblock %}

{% block Header-slider %}
{% endblock %}

{% block wrap %}
<div class="wrap">
    <div class="row Header-rowMain">
        <div class="row-block Header-logo"><a class="logo" href="../index.html"><img class="logo-image"
                                                                                     src="{% static 'assets/img/logo.png' %}"
                                                                                     alt="logo.png"/></a>
        </div>
    </div>
</div>
{% endblock %}
{% block content %}
<div class="wrapper">
    <div class="header">
        <h3 class="sign-in">Восстановление пароля (1/2)</h3>
        <h5>Для восстановления пароля введите адрес электронной почты, на которую зарегистрирована учетная
            запись</h5>
    </div>

    <form action="#">

        <div>


            <input class="user-input" type="email" name="login" id="name" placeholder="E-mail"/>
        </div>
        <div>
            <input type="submit" value="Получить проверочный код"/>
        </div>
        <a class="registr" href="1/registr.html">
            Вход
        </a>
    </form>
</div>
{% endblock %}

shope/templates/authapp/password.html
{% extends 'base.html' %}
{% load static %}
{% block Header-searchWrap %}
{% endblock %}
{% block Header-slider %}
{% endblock %}
{% block wrap %}
<div class="wrap">
    <div class="row Header-rowMain">
        <div class="row-block Header-logo"><a class="logo" href="../index.html"><img class="logo-image"
                                                                                     src="{% static 'assets/img/logo.png' %}"
                                                                                     alt="logo.png"/></a>
        </div>
    </div>
</div>
{% endblock %}
{% block content %}
<div class="wrapper">
    <div class="header">
        <h3 class="sign-in">Восстановление пароля (2/2)</h3>
        <h5>Придумайте новый пароль для учетной записи</h5>
    </div>

    <form action="#">
        <div>
            <input type="password" name="pass" id="name" placeholder="Пароль"/>
        </div>
        <div>
            <input type="submit" value="Сохранить пароль"/>
        </div>
    </form>
</div>

{% endblock %}

shope/templates/authapp/registr.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block Header-searchWrap %}
{% endblock %}

{% block Header-slider %}
{% endblock %}

{% block wrap %}
<div class="wrap">
    <div class="row Header-rowMain">
        <div class="row-block Header-logo"><a class="logo" href="{% url 'coreapp:index' %}"><img class="logo-image"
                                                                                         src="{% static 'assets/img/logo.png' %}"
                                                                                         alt="logo.png"/></a>
        </div>
    </div>
</div>
{% endblock %}
{% block content %}
<div class="wrapper wrap-reg">
    {% for message in messages %}
        {{ message }}
    {% endfor %}
    <div class="header">
        <h3 class="sign-in">{% translate 'Registration' %}</h3>
    </div>
    <div class="clear"></div>
    <form action="{% url 'authapp:signup' %}" method="post">{% csrf_token %}
        <div class="form-wrap">
            <div>
                {{ form.first_name }}
                <!--                <input class="user-input" type="text" name="first_name" id="name" placeholder="Имя"/>-->
            </div>
            <div>
                {{ form.last_name }}
                <!--                <input class="user-input" type="text" name="last_name" id="name" placeholder="Фамилия"/>-->
            </div>
            <div>
                {{ form.middle_name }}
                <!--                <input class="user-input" type="text" name="middle_name" id="name" placeholder="Отчество"/>-->
            </div>
            <div>
                {{ form.email }}
                <!--                <input class="user-input" type="email" name="email" id="name" placeholder="E-mail"/>-->
            </div>
            <div>
                {{ form.password1 }}
                <!--                <input type="password" name="pass" id="name" placeholder="Пароль"/>-->
            </div>
            <div>
                {{ form.password2 }}
                <!--                <input type="password" name="pass2" id="name" placeholder="Подтверждение пароля"/>-->
            </div>
            <input class="input-reg" type="submit" value="{% translate 'Register' %}"/>
            <a class="registr log-in" href="{% url 'authapp:login' %}">
                {% translate 'Log in' %}
            </a>
        </div>
        <div class="clear"></div>
    </form>
</div>
{% endblock %}

shope/templates/authapp/set_password.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block Header-searchWrap %}
{% endblock %}
{% block Header-slider %}
{% endblock %}
{% block wrap %}
<div class="wrap">
    <div class="row Header-rowMain">
        <div class="row-block Header-logo"><a class="logo" href="{% url 'coreapp:index' %}"><img class="logo-image"
                                                                                     src="{% static 'assets/img/logo.png' %}"
                                                                                     alt="logo.png"/></a>
        </div>
    </div>
</div>
{% endblock %}
{% block content %}
<div class="wrapper">
    <div class="error-login">
    {{form.new_password1.errors}}
    {{form.new_password2.errors}}
    </div>
    <div class="header">
        <h3 class="sign-in">{% translate 'Restore password' %} (2/2)</h3>
        <h5 class="set-pass">{% translate 'Think of a new password for the account' %}</h5>
    </div>
    <form action="" method="post">{% csrf_token %}
        <div>
<!--            {{ form.new_password1.errors }}-->
            {{ form.new_password1 }}
            <!--            <input type="password" name="pass" id="name" placeholder="Пароль"/>-->
        </div>
        <div>
<!--            {{ form.new_password2.errors }}-->
            {{ form.new_password2 }}
        </div>
        <div>
            <input type="submit" value="{% translate 'Save password' %}"/>
        </div>
    </form>
</div>

{% endblock %}