shope/authapp/urls.py
from django.urls import path
from authapp.views import UserLoginView, UserLogoutView, UserSignUpView, \
    verify_user, UserPassResetView, UserPassChangeView

app_name = 'authapp'

urlpatterns = [
    path('forgot-password/', UserPassResetView.as_view(),
         name='forgot_pass'),
    path('login/', UserLoginView.as_view(),
         name='login'),
    path('set-password/<uidb64>/<token>/', UserPassChangeView.as_view(),
         name='set_pass'),
    path('signup/', UserSignUpView.as_view(),
         name='signup'),
    path('logout/', UserLogoutView.as_view(),
         name='logout'),
    path('verified/<str:email>/<str:key>/', verify_user,
         name='verified'
         ),
]

shope/cartapp/urls.py
from django.urls import path
from cartapp.views import (
    CartItemListView,
    AddToCartAjaxView,
    ReduceFromCartAjaxView,
    DeleteCartItemAjaxView,
    ChangeQuantityCartAjaxView
)

app_name = 'cartapp'
urlpatterns = [
    path('',
         CartItemListView.as_view(), name='cart'),
    path('catalog/ajax_add/',
         AddToCartAjaxView.as_view(), name='ajax_add_product'),
    path('catalog/ajax_reduce/',
         ReduceFromCartAjaxView.as_view(), name='ajax_reduce_product'),
    path('catalog/ajax_delete/',
         DeleteCartItemAjaxView.as_view(), name='ajax_delete_product'),
    path('catalog/ajax_change-count/',
         ChangeQuantityCartAjaxView.as_view(), name='ajax_change_count'),
]

shope/coreapp/urls.py
from django.urls import path
from .views import IndexView

app_name = 'coreapp'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    # path('clear_cache/<str:cache_name>', clear_cache, name="clear_cache"),
]

shope/orderapp/urls.py
from django.urls import path
from orderapp.views import OrderListView, OrderDetailView, \
    AddOrderView, export_orders_to_xls, EditOrderView, RemoveOrderItemView


app_name = 'orderapp'

urlpatterns = [

    path('', AddOrderView.as_view(), name='add_order'),
    path('editorder/<int:order_pk>/', EditOrderView.as_view(), name='edit_order'),
    path('removeitem/<int:order_pk>/<int:orderitem_pk>/', RemoveOrderItemView.as_view(), name='remove_item'),
    path('historyorder/', OrderListView.as_view(), name='history_order'),
    path('oneorder/<int:order_pk>/', OrderDetailView.as_view(), name='oneorder'),
    path('historyorder/export_orders/', export_orders_to_xls, name='export_orders'),
]

shope/profileapp/urls.py
from django.urls import path
from .views import ProfileDetailView, ProfileUpdateView, ViewedProductsListView

app_name = 'profileapp'

urlpatterns = [
    path('account/', ProfileDetailView.as_view(), name='account'),
    path('profile/', ProfileUpdateView.as_view(), name='profile_update'),
    path('viewed/', ViewedProductsListView.as_view(), name='viewed_products'),
]

shope/shope/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
import os
from django.conf.urls.i18n import i18n_patterns

urlpatterns = []

urlpatterns += i18n_patterns(
    path('', include('coreapp.urls')),
    path('admin/', admin.site.urls),
    path('order/', include('orderapp.urls')),
    path('profile/', include('profileapp.urls')),
    path('products/', include('productsapp.urls')),
    path('payment/', include('paymentapp.urls')),
    path('auth/', include('authapp.urls')),
    path('cart/', include('cartapp.urls')),
)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

if not os.getenv("DOCKER"):
    urlpatterns += [path('silk/', include('silk.urls', namespace='silk'))]

shope/cartapp/models/cart.py
# flake8: noqa
from django.db import models
from django.utils.translation import gettext_lazy as _
from authapp.models import User
from coreapp.models import BaseModel


class Cart(BaseModel):
    """
    Cart model
    """
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='cart',
        verbose_name=_('user'))

    class Meta:
        verbose_name = _('cart')
        verbose_name_plural = _('carts')

    def __str__(self):
        return f'{self.user} cart'

shope/cartapp/models/cartitem.py
# flake8: noqa
from django.db import models
from django.utils.translation import gettext_lazy as _
from coreapp.models import BaseModel
from cartapp.models.cart import Cart
from productsapp.models.product import Product
from productsapp.models.seller import Seller


class CartItem(BaseModel):
    """
    CartItems model
    """
    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
        related_name='cartitems',
        verbose_name=_('product')
    )
    quantity = models.PositiveIntegerField(
        null=False,
        default=1,
        verbose_name=_('quantity')
    )
    cart = models.ForeignKey(
        Cart,
        on_delete=models.CASCADE,
        related_name='items',
        verbose_name=_('cart')
    )
    seller = models.ForeignKey(
        Seller,
        on_delete=models.CASCADE,
        related_name='items',
        verbose_name='seller'
    )
    discounted_price = models.DecimalField(
        default=0,
        verbose_name=_('Discounted price'),
        decimal_places=2,
        max_digits=20

    )

    class Meta:
        verbose_name_plural = _('items in cart')
        verbose_name = _('item in cart')

    def __str__(self):
        return f'{self.product} ({self.quantity})' \

shope/cartapp/forms.py
from django import forms


class InputAmountForm(forms.Form):
    """
    Форма, используемая при работе с корзиной
    """
    count = forms.IntegerField(required=False, min_value=1, max_value=100)
    product_id = forms.IntegerField(required=True)
    seller_id = forms.IntegerField(required=True)

    # count - количество товара

shope/cartapp/views.py
from django.views import View
from django.shortcuts import render
from django.http import JsonResponse
from django.template.loader import render_to_string
from coreapp.utils import AddToCart, SelectCart, ProductDiscounts
from repositories import DiscountRepository, RepCart
from .forms import InputAmountForm
from django.http import HttpResponse

disc_rep = DiscountRepository()
cart_rep = RepCart()


class CartItemListView(View):
    """
    Класс для отображения всех товаров в корзине
    """
    template_name = 'cartapp/cart.html'

    def get(self, request, *args, **kwargs) -> HttpResponse:
        if request.user.is_authenticated:  # пользователь авторизован
            cart = cart_rep.get_cart(user=request.user)
            cart_items = SelectCart.cart_items_list(cart)
            context = {'items': cart_items, 'session': False}
            return render(request, self.template_name, context=context)
        else:  # пользователь не авторизован
            if request.session.get('products', False):  # есть товары в сессии
                items_price = SelectCart. \
                    cart_items_list(session_products=request.session['products']) # noqa
                count_list = [val for val in request.session['products'].values()] # noqa
                session_products = request.session.get('products')
                cart_price, count = SelectCart.get_cart_sum_and_count(
                    session_products=session_products)
                discounted_prices_list, discount = ProductDiscounts. \
                    get_prices_discount_on_cart(
                        cart_price, count, session_products=session_products)
                request.session['prices'] = discounted_prices_list
                request.session.modified = True
                context = {'items': zip(count_list, items_price,
                                        discounted_prices_list),
                           'session': True, 'count_cart': count,
                           'total_amount': round(sum(discounted_prices_list),
                                                 2),
                           'discount': discount}
                return render(request, self.template_name, context)
            else:
                return render(request, self.template_name)


class AjaxUpdateCartView(View):
    method_service = AddToCart.add_to_cart
    full_delete = False  # флаг для удаления всей позиции с товаром

    def post(self, request, **kwargs) -> JsonResponse:
        form = InputAmountForm(request.POST)
        if request.headers.get('x-requested-with') == 'XMLHttpRequest':
            if form.is_valid():  # передано валидное значение count
                cleaned_data = {key: val for key, val in
                                form.cleaned_data.items() if val is not None}
                if self.full_delete:
                    cleaned_data['full'] = True
                if request.user.is_authenticated:  # пользователь авторизован
                    cart = cart_rep.get_cart(user=request.user)  # корзина
                    self.method_service(**cleaned_data, cart=cart)
                    dict_params = SelectCart.get_dict_param_cart(cart)
                    cart_items_html = render_to_string(
                        'cartapp/cart_ajax.html',
                        context={'items': dict_params['cart_items'],
                                 'cart_sum': round(sum(dict_params['prices_list']), 2),  # noqa
                                 'discount': dict_params['discount'],
                                 })
                    context = {'cart_count': dict_params['cart_count'],
                               'items': cart_items_html,
                               'cart_sum': round(sum(dict_params['prices_list']), 2) # noqa
                               }
                    return JsonResponse(data=context, safe=False)
                else:
                    session_products = request.session.get('products')
                    products = self. \
                        method_service(**cleaned_data, session_products=session_products)  # noqa
                    request.session['products'] = products
                    dict_params = SelectCart.get_dict_param_cart(session_products=products)  # noqa
                    request.session['prices'] = dict_params['prices_list']
                    request.session.modified = True
                    cart_items_html = render_to_string(
                        'cartapp/cart_ajax.html',
                        context={
                            'items': list(zip(
                                dict_params['count_list'],
                                dict_params['items_list'],
                                dict_params['prices_list']
                            )),
                            'session': True, 'discount': dict_params['discount'], # noqa
                            'cart_sum': round(sum(dict_params['prices_list']), 2) # noqa
                        })
                    context = {'items': cart_items_html,
                               'cart_count': dict_params['cart_count'],
                               'cart_sum': round(sum(dict_params['prices_list']), 2) # noqa
                               }
                    return JsonResponse(data=context, safe=False)


class AddToCartAjaxView(AjaxUpdateCartView):
    method_service = AddToCart.add_to_cart


class ReduceFromCartAjaxView(AjaxUpdateCartView):
    method_service = AddToCart.delete_from_cart


class DeleteCartItemAjaxView(AjaxUpdateCartView):
    method_service = AddToCart.delete_from_cart
    full_delete = True


class ChangeQuantityCartAjaxView(AjaxUpdateCartView):
    """
    Класс для изменения количества товара в корзине
    """
    method_service = AddToCart.change_amount

shope/templates/cartapp/cart.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% load get_price %}


{% block title %}
Megano
{% endblock %}

        {% block wrap %}
            <div class="wrap">
                <div class="row Header-rowMain">
                    <div class="row-block Header-logo"><a class="logo" href="{% url 'coreapp:index' %}"><img class="logo-image" src="{% static 'assets/img/logo.png' %}" alt="logo.png" /></a>
                    </div>
                    <nav class="row-block row-block_right Header-menu">
                        <div class="menuModal" id="navigate">
                            <ul class="menu menu_main">
                                <li class="menu-item"><a class="menu-link" href="{% url 'coreapp:index' %}">{% translate 'Home' %}</a>
                                </li>
                                <li class="menu-item"><a href="{% url 'productsapp:sales' %}"><span class="menu-label menu-label_success">{% translate 'Discounts' %}</span></a><a class="menu-link" href="{% url 'productsapp:catalog' %}">{% translate 'Catalog' %}</a>
                                </li>
                                <li class="menu-item"><a class="menu-link" href="{% url 'productsapp:comparison' %}">{% translate 'Comparison' %}
                                    <span style="
                                        background: #0063d1;
                                        position: absolute;
                                        right: -14px;
                                        top: 0px;
                                        min-width: 23px;
                                        font-size: 12px;
                                        letter-spacing: -0.6px;
                                        color: #fff;
                                        padding: 2px;
                                        line-height: 1.2em;
                                        display: flex;
                                        align-items: center;
                                        justify-content: center;
                                        border: 3px solid #fff;
                                        border-radius: 100px;
                                    ">{% firstof count_comparis '0' %}</span></a>
                                </li>
                            </ul>
                        </div>
                    </nav>
                    <div class="row-block">

                        <div class="CartBlock">
                            <div class="dropdown">
                                {% if user.is_authenticated %}
                                <button class="dropbtn"><img class="CartBlock-img" src="{% static 'assets/img/icons/loon-icon.svg' %}" alt="loon-icon.svg" /></button>
                                <div class="dropdown-content">
                                    <a class="dropdown-content-a" href="{% url 'profileapp:account' %}">{% translate 'Private Office' %}</a>
                                    {% if user.is_staff %}
                                    <a class="dropdown-content-a" href="#">{% translate 'Administrative section' %}</a>
                                    {% endif %}
                                    <a class="dropdown-content-a" href="{% url 'authapp:logout' %}">{% translate 'Output' %}</a>
                                </div>
                                {% endif %}
                            </div>
                            {% if session %}
                            <a class="CartBlock-block" href="{% url 'cartapp:cart' %}"><img class="CartBlock-img" src="{% static 'assets/img/icons/cart.svg' %}" alt="{% static 'cart.svg'%}" /><span class="CartBlock-amount">{% firstof count_cart '0' %}</span></a>
                            <div class="CartBlock-block"><span class="CartBlock-price">{% firstof total_amount '0' %}</span>
                            </div>
                            {% else %}
                            <a class="CartBlock-block" href="{% url 'cartapp:cart' %}"><img class="CartBlock-img" src="{% static 'assets/img/icons/cart.svg' %}" alt="{% static 'cart.svg'%}" /><span class="CartBlock-amount">{% firstof cart_count '0' %}</span></a>
                            <div class="CartBlock-block"><span class="CartBlock-price">{% firstof cart_sum '0' %}</span>
                            </div>
                            {% endif %}
                        </div>
                    </div>
                    <div class="row-block Header-trigger"><a class="menuTrigger" href="#navigate">
                            <div class="menuTrigger-content">{% translate 'Show navigation' %}
                            </div><span></span><span></span><span></span>
                        </a>
                    </div>
                </div>
            </div>
        {% endblock %}
{% block Header-slider %}
{% endblock %}

{% block content %}
<div class="Middle Middle_top">
    <div class="Section">
        <div class="wrap">

            <form class="form Cart" action="#" method="post">
                {% csrf_token %}

                    {% include 'cartapp/cart_ajax.html' %}


            </form>
        </div>
    </div>
</div>
{% endblock %}

shope/templates/cartapp/cart_ajax.html
{% load static %}
{% load i18n %}
{% load get_price %}


{% if items %}
    {% if discount %}
    {% if discount.required_sum or discount.required_quantity %}
        <h3 class="type-discount">{% translate 'You have received a' %} {{discount.value|floatformat:"0" }}% {% translate 'discount on your cart' %}</h3>
    {% elif discount.products %}
        <h3 class="type-discount">{% translate 'You have received a' %} {{discount.value|floatformat:"0"}}% {% translate 'discount on a set of products' %}</h3>
    {% endif %}
    {% endif %}
    {% if session %}
        {% for count, item, discounted_price in items %}

                <div class="Cart-product">
                    <div class="Cart-block Cart-block_row">
                        <div class="Cart-block Cart-block_pict">
                            <a class="Cart-pict" href="#">
                                <img class="Cart-img" src="{{item.product.product_images.first.image.url}}" alt="card.jpg"/>
                            </a>
                        </div>
                        <div class="Cart-block Cart-block_info"><a class="Cart-title"
                                                                   href="{% url 'productsapp:product_detail' item.product.pk %}">{{item.product.name}}</a>
                            <div class="Cart-desc">{{item.product.description}}
                            </div>
                             <br>
                            <div class="seller-cart">
                                <a class="Cart-title" href="{% url 'productsapp:seller_detail' item.seller.pk %}">
                                                            {% translate 'Seller' %}: {{ item.seller.name }}
                                </a>
                            </div>
                        </div>
                        <div class="Cart-block Cart-block_price">
                            {% get_price item.value count as price %}
                            {% if price != discounted_price %}
                                <div class="Cart-price discounted_price">
                                    {{price}}&nbsp;&#8381;
                                </div>
                                <div class="Cart-price">
                                    {{discounted_price}}&nbsp;&#8381;
                                </div>
                            {% else %}
                                <div class="Cart-price">
                                    {{price}}&nbsp;&#8381;
                                </div>
                            {% endif %}
                        </div>
                    </div>
                    <div class="Cart-block Cart-block_row">
                        <div class="Cart-block Cart-block_seller">
                            <!-- - var options = setOptions(items, ['value', 'selected', 'disabled']);-->

                        </div>
                        <div class="Cart-block Cart-block_amount">
                            <div class="Cart-amount">
                                <div class="Amount">
                                    <button class="Amount-remove" data-product={{item.product.pk}} data-seller={{item.seller.pk}} type="button" data-href="{% url 'cartapp:ajax_reduce_product'%}">
                                    </button>
                                    <input class="Amount-input form-input" name="amount" type="text"
                                           value={{count}} disabled>
                                    <button class="Amount-add" type="button" data-product={{item.product.pk}} data-seller={{item.seller.pk}} data-href="{% url 'cartapp:ajax_add_product'%}">

                                    </button>
                                </div>
                            </div>
                        </div>
                        <div class="Cart-block Cart-block_delete">
                            <button class="Cart-delete" type="button" data-product={{item.product.pk}} data-seller={{item.seller.pk}} data-href="{% url 'cartapp:ajax_delete_product'%}"><img
                                src="{% static 'assets/img/icons/card/delete.svg' %}" alt="delete.svg"/></button>
                        </div>
                    </div>
                </div>
        {% empty %}
            <h2 class="empty-cart">{% translate 'No products in cart' %}</h2>
            <div></div>
        {% endfor %}
                    <div class="Cart-total">
                        <div class="Cart-block Cart-block_total">
                            <strong class="Cart-title">{% translate 'Total' %}:</strong>
                            <span class="Cart-price">{% firstof cart_sum '0' %}&nbsp;&#8381;</span>
                        </div>
                        <div class="Cart-block">
                            <a class="btn btn_success btn_lg" href="{% url 'authapp:login' %}?next={% url 'cartapp:cart' %}">{% translate 'Log in to continue' %}</a>
                        </div>
                    </div>
    {% else %}
        {% for item in items %}
            <div class="Cart-product">
                <div class="Cart-block Cart-block_row">
                    <div class="Cart-block Cart-block_pict">
                        <a class="Cart-pict" href="{% url 'productsapp:product_detail' item.product.pk %}">
                            <img class="Cart-img" src="{{item.product.product_images.first.image.url}}" alt="card.jpg"/>
                        </a>
                    </div>
                    <div class="Cart-block Cart-block_info"><a class="Cart-title"
                                                               href="{% url 'productsapp:product_detail' item.product.pk %}">{{item.product.name}}</a>
                        <div class="Cart-desc">{{item.product.description}}
                        </div>
                        <br>
                        <div class="seller-cart">
                            {% translate 'Seller' %}: {{item.seller.name}}
                        </div>
                    </div>
                    <div class="Cart-block Cart-block_price">
                        {% get_price item.price item.quantity as price %}
                        {% if price != item.discounted_price %}
                            <div class="Cart-price discounted_price">
                                {{ price }}&nbsp;&#8381;
                            </div>
                            <div class="Cart-price" id="">
                                {{item.discounted_price}}&nbsp;&#8381;
                            </div>
                        {% else %}
                            <div class="Cart-price">
                                {{price}}&nbsp;&#8381;
                            </div>
                        {% endif %}
                    </div>
                </div>
                <div class="Cart-block Cart-block_row">
                    <div class="Cart-block Cart-block_seller">
                        <!-- - var options = setOptions(items, ['value', 'selected', 'disabled']);-->

                    </div>
                    <div class="Cart-block Cart-block_amount">
                        <div class="Cart-amount">
                            <div class="Amount">
                                <button class="Amount-remove" type="button" data-product={{item.product.pk}} data-seller={{item.seller.pk}} data-href="{% url 'cartapp:ajax_reduce_product' %}">
                                    </button>
                                <input class="Amount-input form-input" name="amount" type="text" value="{{ item.quantity }}" disabled >
                                <button class="Amount-add" type="button" data-product={{item.product.pk}} data-seller={{item.seller.pk}} data-href="{% url 'cartapp:ajax_add_product' %}">
                                    </button>
                                </button>
                            </div>
                        </div>
                    </div>
                    <div class="Cart-block Cart-block_delete"><button class="Cart-delete" type="button" data-product={{item.product.pk}} data-seller={{item.seller.pk}} data-href="{% url 'cartapp:ajax_delete_product' %}"><img
                            src="{% static 'assets/img/icons/card/delete.svg' %}" alt="delete.svg"/></button>
                    </div>
                </div>
            </div>
        {% endfor %}

            <div class="Cart-total">
                                <div class="Cart-block Cart-block_total">
                                    <strong class="Cart-title">{% translate 'Total' %}:
                                    </strong>

                                    <span class="Cart-price">{% firstof cart_sum '0' %} &#x20bd</span>

                                </div>
                                <div class="Cart-block"><button class="btn btn_success btn_lg" type="submit" formmethod="post" formaction="{% url 'orderapp:add_order' %}">{% translate 'Place an order' %}</button>
                                </div>
                            </div>


    {% endif %}
{% else %}
    <h2 class="empty-cart">{% translate 'No products in cart' %}</h2>
    <div></div>
{% endif %}