shope/orderapp/urls.py
from django.urls import path
from orderapp.views import OrderListView, OrderDetailView, \
    AddOrderView, export_orders_to_xls, EditOrderView, RemoveOrderItemView


app_name = 'orderapp'

urlpatterns = [

    path('', AddOrderView.as_view(), name='add_order'),
    path('editorder/<int:order_pk>/', EditOrderView.as_view(), name='edit_order'),
    path('removeitem/<int:order_pk>/<int:orderitem_pk>/', RemoveOrderItemView.as_view(), name='remove_item'),
    path('historyorder/', OrderListView.as_view(), name='history_order'),
    path('oneorder/<int:order_pk>/', OrderDetailView.as_view(), name='oneorder'),
    path('historyorder/export_orders/', export_orders_to_xls, name='export_orders'),
]

shope/productsapp/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from productsapp.views import (
    ProductListView,
    AddReviewView,
    ProductComparisonView,
    ProductDetailView,
    AddToComparisonView,
    RemoveFromComparisonView,
    export_product_to_xls,
    DiscountsListView,
    DiscountSetDetailView,
    DiscountCartDetailView,
    seller_detail_view,
)

app_name = 'productsapp'

urlpatterns = [
    path('catalog/', ProductListView.as_view(), name="catalog"),
    path('catalog/<int:product_id>/', ProductDetailView.as_view(), name="product_detail"),
    path('catalog/<int:product_id>/add_review/', AddReviewView.as_view(), name="add_review"),
    path('catalog/<int:product_id>/add_to_comparison/', AddToComparisonView.as_view(), name="add_to_comparison"),
    path('catalog/export/', export_product_to_xls, name="export_product"),
    path('comparison/', ProductComparisonView.as_view(), name="comparison"),
    path('comparison/<int:product_id>', RemoveFromComparisonView.as_view(), name="remove_from_comp"),
    path('sale/', DiscountsListView.as_view(), name="sales"),
    path('sale/<int:elem_id>/set/', DiscountSetDetailView.as_view(), name="discount_set_detail"),
    path('sale/<int:elem_id>/cart/', DiscountCartDetailView.as_view(), name="discount_cart_detail"),
    path('sellers/<int:seller_id>/', cache_page(timeout=86400,
                                                key_prefix="seller_detail"
                                                )(seller_detail_view), name="seller_detail"),
]

shope/profileapp/urls.py
from django.urls import path
from .views import ProfileDetailView, ProfileUpdateView, ViewedProductsListView

app_name = 'profileapp'

urlpatterns = [
    path('account/', ProfileDetailView.as_view(), name='account'),
    path('profile/', ProfileUpdateView.as_view(), name='profile_update'),
    path('viewed/', ViewedProductsListView.as_view(), name='viewed_products'),
]

shope/shope/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
import os
from django.conf.urls.i18n import i18n_patterns

urlpatterns = []

urlpatterns += i18n_patterns(
    path('', include('coreapp.urls')),
    path('admin/', admin.site.urls),
    path('order/', include('orderapp.urls')),
    path('profile/', include('profileapp.urls')),
    path('products/', include('productsapp.urls')),
    path('payment/', include('paymentapp.urls')),
    path('auth/', include('authapp.urls')),
    path('cart/', include('cartapp.urls')),
)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

if not os.getenv("DOCKER"):
    urlpatterns += [path('silk/', include('silk.urls', namespace='silk'))]

shope/orderapp/models.py
from django.db import models
from coreapp.models import BaseModel
from authapp.models import User
from productsapp.models import Seller, Product
from coreapp.enums import ORDER_STATUSES, DELIVERY_TYPE, \
    DEFAULT, NOT_PAID_STATUS
from django.utils.translation import gettext_lazy as _
from phonenumber_field.modelfields import PhoneNumberField


class Order(BaseModel):
    """
    Класс модели заказа
    """
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name=_('user'),
        related_name='orders'
    )

    fio = models.CharField(
        max_length=100,
        verbose_name=_('FIO')
    )

    phone_number = PhoneNumberField(
        blank=True,
        verbose_name=_('phone number')
    )

    status = models.CharField(
        max_length=20,
        verbose_name=_('status'),
        choices=ORDER_STATUSES,
        default=NOT_PAID_STATUS
    )

    city = models.CharField(
        max_length=50,
        verbose_name=_('city'),
    )

    address = models.CharField(
        max_length=100,
        verbose_name=_('address')
    )

    delivery_type = models.CharField(
        max_length=20,
        verbose_name=_('delivery type'),
        choices=DELIVERY_TYPE,
        default=DEFAULT
    )

    delivery_price = models.DecimalField(
        max_digits=8,
        decimal_places=2,
        verbose_name=_('delivery price')
    )

    total_price = models.DecimalField(
        max_digits=8,
        decimal_places=2,
        verbose_name=_('total price')
    )

    total_discounted_price = models.DecimalField(
        max_digits=8,
        decimal_places=2,
        verbose_name=_('total discounted price')
    )

    def __str__(self):
        return f'Order {self.id}'

    class Meta:
        verbose_name = _('order')
        verbose_name_plural = _('orders')


class OrderItem(BaseModel):
    """
    Класс модели товара в заказе
    """
    order = models.ForeignKey(
        Order,
        related_name='order_items',
        on_delete=models.CASCADE,
        verbose_name=_('order')
    )

    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
        verbose_name=_('product'),
        related_name='ordered'
    )

    count = models.PositiveSmallIntegerField(
        verbose_name=_('count')
    )

    seller = models.ForeignKey(
        Seller,
        on_delete=models.CASCADE,
        verbose_name=_('seller')
    )

    price = models.DecimalField(
        max_digits=8,
        decimal_places=2,
        verbose_name=_('price'))

    discounted_price = models.DecimalField(
        max_digits=8,
        decimal_places=2,
        verbose_name=_('discounted price'))

    def __str__(self):
        return f'{self.product} x{self.count}'

    class Meta:
        verbose_name = _('order item')
        verbose_name_plural = _('order items')

shope/orderapp/forms.py
from django import forms
from orderapp.models import Order


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ('fio', 'phone_number', 'city', 'address', 'delivery_type')
        widgets = {'delivery_type': forms.RadioSelect(),
                   'address': forms.Textarea()}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['fio'].required = True
        self.fields['fio'].widget.attrs['class'] = 'form-input'
        self.fields['phone_number'].required = True
        self.fields['phone_number'].widget.attrs['class'] = 'form-input'
        self.fields['phone_number'].widget.attrs[
            'placeholder'] = '+79991112233'
        self.fields['city'].required = True
        self.fields['city'].widget.attrs['class'] = 'form-input'
        self.fields['address'].required = True
        self.fields['address'].widget.attrs['class'] = 'form-textarea'
        self.fields['address'].widget.attrs['autocomplete'] = 'on'
        for name, field in self.fields.items():
            field.widget.attrs['id'] = name
            field.widget.attrs['data-validate'] = 'require'

shope/orderapp/views.py
from django.views.generic import View
from profileapp.forms import ProfileForm
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse
from django.http import HttpResponseRedirect


class OrderView(LoginRequiredMixin, View):
    template_name = 'orderapp/order.html'
    login_url = reverse_lazy('authapp:login')

    def get(self, request):
        context = {
            'profile_form': ProfileForm(
                instance=self.request.user.profile),
        }
        return render(request, self.template_name, context)

    def post(self, request):
        return HttpResponseRedirect(reverse('orderapp:order'))

shope/orderapp/views/add_order.py
from django.views.generic import View
from django.shortcuts import HttpResponseRedirect, reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from coreapp.utils.select_cart import SelectCart
from repositories.cart_repository import RepCartItem
from repositories import RepCart
from repositories import (
    OrderUpdateRepository,
    OrderItemUpdateRepository,
    ConfigSelectRepository)

from coreapp.utils import ProductDiscounts


rep_cart = RepCart()
rep_cartitem = RepCartItem()
rep_order = OrderUpdateRepository()
rep_orderitem = OrderItemUpdateRepository()
rep_config = ConfigSelectRepository()


class AddOrderView(LoginRequiredMixin, View):
    """Класс-view для создания нового заказа"""

    def post(self, request):

        user = request.user
        cart = rep_cart.get_cart(user=user)
        count = SelectCart.cart_all_products_amount(cart=cart)
        cart_price = SelectCart.cart_total_amount(cart=cart)
        total_sum = rep_cart.get_total_amount(cart)
        discounted_sum = sum(ProductDiscounts.get_prices_discount_on_cart(
            cart_price, count, cart=cart)[0])
        sellers = rep_cartitem.sellers_amount(cart.pk)

        delivery_price = int(
            rep_config.get_config_value_by_name('DELIVERY_PRICE')
        )
        # доставка бесплатная если все товары от одного продавца и
        # сумма заказа больше требуемой
        if discounted_sum > int(
                rep_config.get_config_value_by_name('FREE_DELIVERY_SUM')
        ) and sellers == 1:
            delivery_price = 0

        order = rep_order.save(  # создание нового заказа
            user=request.user,
            delivery_price=delivery_price,
            total_price=total_sum + delivery_price,
            total_discounted_price=discounted_sum + delivery_price
        )

        # перенос позиций из корзины в заказ
        cart_items = SelectCart.cart_items_list(cart)
        rep_orderitem.create_with_cartitems(
            order=order,
            cart_items=cart_items)
        rep_cartitem.delete(cart_items)  # очистка корзины

        return HttpResponseRedirect(reverse('orderapp:edit_order',
                                            kwargs={'order_pk': order.pk}))

shope/orderapp/views/edit_order.py
from django.views.generic import View
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from orderapp.forms import OrderForm
from paymentapp.forms import PaymentForm
from repositories import OrderRepository, OrderItemSelectRepository

order_rep = OrderRepository()
orderitem_rep = OrderItemSelectRepository()


class EditOrderView(LoginRequiredMixin, View):
    """Класс-view для редактирования заказа"""

    template_name = 'orderapp/order.html'

    def get(self, request, **kwargs):
        order = order_rep.get_order_by_id(kwargs['order_pk'])
        order_items = orderitem_rep.get_all_items(order=order)

        # Предзаполняем заказ данными из профиля
        if not (order.fio and order.phone_number):
            if request.user.profile.fio.strip():
                order.fio = request.user.profile.fio
            order.phone_number = request.user.profile.phone_number

        order_form = OrderForm(instance=order)

        payment_form = PaymentForm()
        payment_form.fields[
            'total_sum'].initial = order.total_discounted_price

        context = {
            'order_form': order_form,
            'payment_form': payment_form,
            'order': order,
            'order_items': order_items,
        }
        return render(request, self.template_name, context)

shope/orderapp/views/export_orders.py
from io import BytesIO

from django.http import HttpRequest, HttpResponse
import pandas as pd

from repositories import OrderRepository

_order_repository = OrderRepository()


def export_orders_to_xls(request: HttpRequest)\
        -> HttpResponse:
    orders = _order_repository.get_orders_by_user_id(
        user_id=request.user.id
    )
    excel_file = BytesIO()
    excel_writer = pd.ExcelWriter(excel_file)
    result = dict()
    for order in orders:
        for name_field in order._meta.fields:
            if name_field.name not in result.keys():
                result[name_field.name] = list()
            if name_field.name not in (
                    "created_at",
                    "updated_at",
            ):
                result[name_field.name].append(
                    order.__getattribute__(str(name_field.name))
                )
            else:
                result[name_field.name].append(order.__getattribute__(
                    str(name_field.name)).isoformat(sep=" ")
                                               )

    df = pd.DataFrame(
        result
    )
    df.to_excel(excel_writer, sheet_name='orders')

    excel_writer.close()
    excel_file.seek(0)

    response = HttpResponse(
        excel_file.read(),
        content_type='application/vnd.openxmlformats-'
                     'officedocument.spreadsheetml.sheet',
    )
    response[
        'Content-Disposition'
    ] = 'attachment; filename=orders.xlsx'
    response['Set-Cookie'] = 'fileDownload=true; path=/'
    return response

shope/orderapp/views/order_detail.py
from django.views.generic import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from repositories import OrderRepository, OrderItemSelectRepository

order_rep = OrderRepository()
orderitem_rep = OrderItemSelectRepository()


class OrderDetailView(LoginRequiredMixin, DetailView):
    """ Класс-view для детальной информации по заказу """

    template_name = 'orderapp/oneorder.html'

    def get_object(self, queryset=None):
        order = order_rep.get_order_by_id(self.kwargs['order_pk'])
        return order

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        order = order_rep.get_order_by_id(self.kwargs['order_pk'])
        order_items = orderitem_rep.get_all_items(order)
        context['order_items'] = order_items

        return context

shope/orderapp/views/orders_list.py
from django.views.generic import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from repositories import OrderRepository

order_rep = OrderRepository()


class OrderListView(LoginRequiredMixin, ListView):
    """ Класс-view для заказов """

    template_name = 'orderapp/historyorder.html'
    ordering = '-created_at'

    def get_queryset(self):
        return order_rep.get_all_by_user(self.request.user.id)

shope/orderapp/views/remove_orderitem.py
from django.views.generic import View
from django.shortcuts import HttpResponseRedirect, reverse
from repositories import OrderItemUpdateRepository, OrderRepository
from repositories import OrderItemSelectRepository
from django.contrib.auth.mixins import LoginRequiredMixin

rep_sel_orderitem = OrderItemSelectRepository()
rep_upd_orderitem = OrderItemUpdateRepository()
rep_order = OrderRepository()


class RemoveOrderItemView(LoginRequiredMixin, View):
    """Класс-представление для удаление позиции из заказа"""

    def get(self, request, order_pk: int, orderitem_pk: int):

        order = rep_order.get_order_by_id(order_pk)
        order_items = rep_sel_orderitem.get_all_items(order=order)

        # В заказе должна быть хотя бы одна позиция
        if order_items.count() > 1:
            rep_upd_orderitem.delete(orderitem_pk)

        return HttpResponseRedirect(reverse(
            'orderapp:edit_order', kwargs={'order_pk': order_pk}))

shope/templates/orderapp/historyorder.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}


{% block title %}
    Megano
{% endblock %}


{% block Header-slider %}
{% endblock %}

{% block content %}
<div class="Middle Middle_top">
        <div class="Section Section_column Section_columnLeft">
            <div class="wrap">
                <div class="Section-column">
                    <div class="Section-columnSection">
                        <header class="Section-header">
                            <strong class="Section-title">Навигация
                            </strong>
                        </header>
                        <div class="Section-columnContent">
                            <div class="NavigateProfile">
                                <ul class="menu menu_vt">
                                    <li class="menu-item"><a class="menu-link" href="{% url 'profileapp:account' %}">{% translate 'Personal account' %}</a>
                                    </li>
                                    <li class="menu-item"><a class="menu-link" href="{% url 'profileapp:profile_update' %}">{% translate 'Profile' %}</a>
                                    </li>
                                    <li class="menu-item_ACTIVE menu-item"><a class="menu-link" href="{% url 'orderapp:history_order' %}">{% translate 'Order history' %}</a>
                                    </li>
                                    <li class="menu-item"><a class="menu-link" href="{% url 'profileapp:viewed_products' %}">{% translate 'Viewed products' %}</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="Section-content">
                    <div class="Orders">
                        {% for order in order_list %}
                            <div class="Order Order_anons">
                                <div class="Order-personal">
                                    <div class="row">
                                        <div class="row-block"><a class="Order-title" href="{% url 'orderapp:oneorder' order.pk %}">{% translate 'Order' %}&#32;<span class="Order-numberOrder">{{ order.pk }}</span>&#32;{% translate 'from' %}&#32;<span class="Order-dateOrder">{{ order.created_at | date:"d.m.Y"}}</span></a>
                                        </div>
                                        <div class="row-block">
                                            <div class="Order-info Order-info_delivery">
                                                <div class="Order-infoType">{% translate 'Type of delivery' %}:
                                                </div>
                                                <div class="Order-infoContent">{{ order.delivery_type }}</div>
                                            </div>
                                            <div class="Order-info Order-info_pay">
                                                <div class="Order-infoType">{% translate 'Payment' %}:
                                                </div>
                                                <div class="Order-infoContent">Оплата картой</div>
                                            </div>
                                            <div class="Order-info">
                                                <div class="Order-infoType">{% translate 'Total cost' %}:
                                                </div>
                                                <div class="Order-infoContent"><span class="Order-price">{{ order.total_discounted_price}}&#8381;</span>
                                                </div>
                                            </div>
                                            <div class="Order-info Order-info_status">
                                                <div class="Order-infoType">{% translate 'Status' %}:
                                                </div>
                                                <div class="Order-infoContent">{{ order.status }}</div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        {% endfor %}
                    </div>
                    {% if order_list %}
                        <form action="{% url 'orderapp:export_orders' %}" method="post">
                            {% csrf_token %}
                            <button class="btn btn_primary" type="submit" style="text-align: right; margin-top: 1em">
                                {% translate 'Export orders' %}
                            </button>
                        </form>
                    {% endif %}
                </div>
            </div>
        </div>
</div>
{% endblock %}

shope/templates/orderapp/oneorder.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}


{% block title %}
    Megano
{% endblock %}


{% block Header-slider %}
{% endblock %}


{% block content %}
    <div class="Middle Middle_top middle_top_oneorder">
        <div class="Middle-top middle_top_oneorder">
            <div class="wrap">
                <div class="Middle-header">
                    <h1 class="Middle-title">{% translate 'Order' %} №{{ object.pk }}
                    </h1>
                </div>
            </div>
        </div>
        <div class="Section">
            <div class="wrap">
                <div class="Section-content">
                    <div class="Orders">
                    </div>
                    <div class="Order">
                        <div class="Order-infoBlock">
                            <div class="Order-personal">
                                <div class="row">
                                    <div class="row-block">
                                        <div class="Order-info Order-info_date">
                                            <div class="Order-infoType">{% translate 'Order date' %}:
                                            </div>
                                            <div class="Order-infoContent">{{ object.created_at | date:"d.m.Y"}}
                                            </div>
                                        </div>
                                        <div class="Order-info">
                                            <div class="Order-infoType">{% translate 'Name' %}:
                                            </div>
                                            <div class="Order-infoContent">{{ object.fio}}
                                            </div>
                                        </div>
                                        <div class="Order-info">
                                            <div class="Order-infoType">{% translate 'Phone number' %}:
                                            </div>
                                            <div class="Order-infoContent">{{ object.phone_number}}
                                            </div>
                                        </div>
                                        <div class="Order-info">
                                            <div class="Order-infoType">{% translate 'E-mail' %}:
                                            </div>
                                            <div class="Order-infoContent">{{ object.user.email}}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row-block">
                                        <div class="Order-info Order-info_delivery">
                                            <div class="Order-infoType">{% translate 'Delivery type' %}:
                                            </div>
                                            <div class="Order-infoContent">{{ object.delivery_type }}
                                            </div>
                                        </div>
                                        <div class="Order-info">
                                            <div class="Order-infoType">{% translate 'City' %}:
                                            </div>
                                            <div class="Order-infoContent">{{ object.city }}
                                            </div>
                                        </div>
                                        <div class="Order-info">
                                            <div class="Order-infoType">{% translate 'Address' %}:
                                            </div>
                                            <div class="Order-infoContent">{{ object.address}}
                                            </div>
                                        </div>
                                        <div class="Order-info Order-info_pay">
                                            <div class="Order-infoType">{% translate 'Payment' %}:
                                            </div>
                                            <div class="Order-infoContent">{% translate 'Bank card (online)' %}
                                            </div>
                                        </div>
                                        <div class="Order-info Order-info_status">
                                            <div class="Order-infoType">{% translate 'Status' %}:
                                            </div>
                                            {% if object.status == "paid" %}
                                                <div class="Order-infoContent">{% translate 'Paid' %}</div>
                                            {% else %}
                                                <div class="Order-infoContent">{% translate 'Not paid for' %}</div>
                                            {% endif %}
                                        </div>
                                        {% if object.status != "paid" %}
                                        <div class="Order-info Order-info_error">
                                            <div class="Order-infoType">{% translate 'Payment failed' %}:
                                            </div>
                                            <div class="Order-infoContent">{% translate 'Payment failed' %}
                                            </div>
                                        </div>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                            <div class="Cart Cart_order">


                                    {% for order_item in order_items %}
                                        <div class="Cart-product">
                                        <div class="Cart-block Cart-block_row">
                                        <div class="Cart-block Cart-block_pict"><a class="Cart-pict" href="#"><img class="Cart-img" src="{{ order_item.product.product_images.first.image.url }}" alt="card.jpg" /></a>
                                        </div>
                                        <div class="Cart-block Cart-block_info"><a class="Cart-title" href="{% url 'productsapp:product_detail' order_item.product.id %}">{{ order_item.product.name }}</a>
                                            <div class="Cart-desc">{{ order_item.product.short_description }}
                                            </div>
                                        </div>
                                        <div class="Cart-block Cart-block_price">
                                                {% if order_item.price != order_item.discounted_price %}
                                                    <div class="Cart-price discounted_price">
                                                        {{order_item.price}}&#8381;
                                                    </div>
                                                    <div class="Cart-price">
                                                        {{order_item.discounted_price}}&#8381;
                                                    </div>
                                                {% else %}
                                                    <div class="Cart-price">
                                                        {{order_item.price}}&#8381;
                                                    </div>
                                                {% endif %}
                                        </div>
                                    </div>
                                        <div class="Cart-block Cart-block_row">

                                        <div class="Cart-block Cart-block_amount">{{ order_item.count }} {% translate 'pcs' %}.
                                        </div>
                                    </div>
                                        </div>
                                    {% endfor %}

                                <div class="Cart-total">
                                    <div class="Cart-block Cart-block_total">
                                        <strong class="Cart-title">{% translate 'Delivery' %}:<span class="Cart-price">{{ order.delivery_price }} &#8381;</span>
                                        </strong>
                                        <strong class="Cart-title">{% translate 'Total' %}:<span class="Cart-price">{{ order.total_discounted_price }} &#8381;</span>
                                        </strong>
                                    </div>
                                    {% if object.status != "paid" %}
                                    <div class="Cart-block"><a class="btn btn_primary btn_lg" href="{% url 'orderapp:edit_order' object.pk %}">{% translate 'Pay' %}</a>
                                    </div>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}